---
- name: Install Clickhouse
  hosts: clickhouse
  become: true

  tasks:
    - name: Download ClickHouse GPG key
      ansible.builtin.get_url:
        url: https://packages.clickhouse.com/repo-archive/CLICKHOUSE-KEY.GPG
        dest: /usr/share/keyrings/clickhouse-key.gpg
    - name: Add ClickHouse APT repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/clickhouse-key.gpg] https://packages.clickhouse.com/deb/stable/ main/
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install ClickHouse packages
      ansible.builtin.apt:
        name:
          - clickhouse-client
          - clickhouse-server
        state: present
    - name: Ensure ClickHouse server is started and enabled
      ansible.builtin.systemd:
        name: clickhouse-server
        enabled: yes
        state: started

- name: Install Vector
  hosts: vector
  become: true
  tasks:
    - name: Download Vector GPG key
      ansible.builtin.get_url:
        url: https://repositories.vector.dev/gpg.key
        dest: /usr/share/keyrings/vector-archive-keyring.gpg
        mode: '0644'

    - name: Add Vector APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/vector-archive-keyring.gpg] https://repositories.vector.dev/apt stable main"
        filename: vector

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install vector package
      ansible.builtin.apt:
        name: vector
        state: present