---
- name: Install Clickhouse
  hosts: clickhouse
  become: true

  tasks:
    - name: Download ClickHouse GPG key
      ansible.builtin.get_url:
        url: https://packages.clickhouse.com/repo-archive/CLICKHOUSE-KEY.GPG
        dest: /usr/share/keyrings/clickhouse-key.gpg
    - name: Add ClickHouse APT repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/clickhouse-key.gpg] https://packages.clickhouse.com/deb/stable/ main/
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install ClickHouse packages
      ansible.builtin.apt:
        name:
          - clickhouse-client
          - clickhouse-server
        state: present
    - name: Ensure ClickHouse server is started and enabled
      ansible.builtin.systemd:
        name: clickhouse-server
        enabled: yes
        state: started

- name: Install Vector
  hosts: vector
  become: true
  tasks:
    - name: Create directory /opt/vector
      ansible.builtin.file:
        path: /opt/vector
        state: directory
        mode: '0755'

    - name: Download Vector DEB package
      ansible.builtin.get_url:
        url: https://packages.timber.io/vector/0.33.0/vector_0.33.0-1_amd64.deb
        dest: /tmp/vector
        mode: '0644'

    - name: Install Vector from DEB package
      ansible.builtin.apt:
        deb: /tmp/vector

    - name: Deploy vector config
      ansible.builtin.template:
        src: templates/vector.yml.j2
        dest: /etc/vector/vector.toml
        mode: '0644'
      notify:
        - Restart Vector

  handlers:
    - name: Restart Vector
      ansible.builtin.systemd:
        name: vector
        state: restarted
        enabled: true
