---
- name: Download ClickHouse GPG key file
  ansible.builtin.get_url:
    url: https://packages.clickhouse.com/CLICKHOUSE-KEY.GPG
    dest: /etc/apt/keyrings/clickhouse.gpg
    mode: '0644'

- name: Add ClickHouse APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/clickhouse.gpg] https://packages.clickhouse.com/deb stable main"
    state: present
    filename: clickhouse

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install ClickHouse packages
  ansible.builtin.apt:
    name:
      - clickhouse-client
      - clickhouse-server
    state: present

- name: Ensure ClickHouse server is started and enabled
  ansible.builtin.service:
    name: clickhouse-server
    state: started
    enabled: true