---
- name: Add ClickHouse APT key
  become: true
  apt_key:
    url: https://packages.clickhouse.com/CLICKHOUSE-KEY.GPG
    state: present

- name: Add ClickHouse APT repository
  become: true
  apt_repository:
    repo: "deb https://packages.clickhouse.com/deb stable main"
    state: present
    filename: clickhouse

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install ClickHouse packages
  become: true
  apt:
    name:
      - clickhouse-client
      - clickhouse-server
    state: present

- name: Ensure ClickHouse service is running
  become: true
  service:
    name: clickhouse-server
    state: started
    enabled: yes