---

- name: Download ClickHouse GPG key
  get_url:
    url: https://packages.clickhouse.com/CLICKHOUSE-KEY.GPG
    dest: /usr/share/keyrings/clickhouse-key.gpg
    mode: '0644'
  become: true

- name: Add ClickHouse APT repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/clickhouse-key.gpg] https://packages.clickhouse.com/deb stable main"
    state: present
    filename: clickhouse
  become: true

- name: Update apt cache
  apt:
    update_cache: true
  become: true

- name: Install ClickHouse packages
  apt:
    name: "{{ clickhouse_packages }}"
    state: present
  become: true

- name: Ensure ClickHouse server is started and enabled
  service:
    name: clickhouse-server
    state: started
    enabled: true
  become: true